FROM golang:1.9-alpine

WORKDIR /go/src/app
COPY . .

EXPOSE 8080
ENV CGO_ENABLED=0
ENV GOOS=linux
RUN ["go", "build", "-a", "-installsuffix", "cgo", "-o", "server"]

FROM scratch
COPY --from=0 /go/src/app/server /
COPY --from=0 /go/src/app/home.html /
CMD ["/server"]