version: '3'
services:
  db:
    image: mongo:3.4.0
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
  demo:
    build: ./
    ports:
      - 80:5000
    environment:
      - DB=db
      - DB_PORT=27017
